# Generated by Django 3.1 on 2022-11-08 10:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 8, 15, 41, 12, 726092)),
        ),
    ]
